import XCTest
import RecorderCore
@testable import Onyx

/// Which file the viewer plays. This is not a free choice: the pipeline's
/// `.cleanup` step deletes `mic.wav`, `system.wav`, `mic_normalized.wav` and
/// `system_normalized.wav`, so for a *finished* meeting the only surviving
/// audio is `mic.m4a` / `system.m4a`. The plan's literal code played
/// `mic_normalized.wav` (falling back to `mic.wav`) — i.e. it would have found
/// nothing at all for every completed meeting.
final class AudioSourceResolverTests: XCTestCase {
    private var tmp: URL!
    private var paths: MeetingPaths!

    override func setUpWithError() throws {
        try super.setUpWithError()
        tmp = FileManager.default.temporaryDirectory
            .appendingPathComponent("onyx-src-\(UUID().uuidString)", isDirectory: true)
        paths = MeetingPaths(root: tmp, slug: "2026-01-01_10h00")
        try FileManager.default.createDirectory(at: paths.audio,
                                               withIntermediateDirectories: true)
    }

    override func tearDownWithError() throws {
        try? FileManager.default.removeItem(at: tmp)
        try super.tearDownWithError()
    }

    private func touch(_ url: URL) throws {
        try Data([0]).write(to: url)
    }

    func test_noAudioAtAllReturnsNil() {
        XCTAssertNil(AudioSourceResolver.resolve(paths: paths))
    }

    /// The completed-meeting case: only the m4a files exist.
    func test_prefersMicM4aWhenBothM4asSurviveCleanup() throws {
        try touch(paths.micM4a)
        try touch(paths.systemM4a)
        XCTAssertEqual(AudioSourceResolver.resolve(paths: paths), paths.micM4a)
    }

    func test_systemOnlyMeetingPlaysSystem() throws {
        try touch(paths.systemM4a)
        XCTAssertEqual(AudioSourceResolver.resolve(paths: paths), paths.systemM4a)
    }

    func test_micOnlyMeetingPlaysMic() throws {
        try touch(paths.micM4a)
        XCTAssertEqual(AudioSourceResolver.resolve(paths: paths), paths.micM4a)
    }

    /// A meeting still recording, or one whose pipeline has not reached
    /// `.cleanup`: the WAVs are there and the m4a is not.
    func test_fallsBackToSurvivingWavsBeforeCleanup() throws {
        try touch(paths.micWav)
        XCTAssertEqual(AudioSourceResolver.resolve(paths: paths), paths.micWav)
        try touch(paths.micNormalized)
        XCTAssertEqual(AudioSourceResolver.resolve(paths: paths), paths.micNormalized,
                       "the normalized WAV is what the pipeline's waveform.json describes")
        try touch(paths.micM4a)
        XCTAssertEqual(AudioSourceResolver.resolve(paths: paths), paths.micM4a,
                       "the m4a is the file that will still be there tomorrow")
    }

    func test_systemWavsAreLastResort() throws {
        try touch(paths.systemWav)
        XCTAssertEqual(AudioSourceResolver.resolve(paths: paths), paths.systemWav)
    }

    /// `waveform.json` is generated by the pipeline from the *mic* stream, so it
    /// may only be reused when the file we play is also a mic stream — otherwise
    /// the drawn waveform would have nothing to do with the audible audio.
    func test_isMicSource() {
        XCTAssertTrue(AudioSourceResolver.isMicSource(paths.micM4a, paths: paths))
        XCTAssertTrue(AudioSourceResolver.isMicSource(paths.micWav, paths: paths))
        XCTAssertTrue(AudioSourceResolver.isMicSource(paths.micNormalized, paths: paths))
        XCTAssertFalse(AudioSourceResolver.isMicSource(paths.systemM4a, paths: paths))
        XCTAssertFalse(AudioSourceResolver.isMicSource(paths.systemWav, paths: paths))
        XCTAssertFalse(AudioSourceResolver.isMicSource(paths.systemNormalized, paths: paths))
    }

    // MARK: - Per-stream resolution (mixed playback)

    /// The completed-meeting case for the mixed player: both streams resolve
    /// independently and both files are handed to the player, mic first.
    func test_resolveSources_returnsBothStreams() throws {
        try touch(paths.micM4a)
        try touch(paths.systemM4a)
        let s = AudioSourceResolver.resolveSources(paths: paths)
        XCTAssertEqual(s.mic, paths.micM4a)
        XCTAssertEqual(s.system, paths.systemM4a)
        XCTAssertEqual(s.urls, [paths.micM4a, paths.systemM4a])
    }

    /// The per-stream preference order (m4a > normalized wav > raw wav) applies
    /// to each stream on its own, and a stream with no file resolves to nil
    /// without hiding the other one.
    func test_resolveSources_perStreamPreferenceOrder() throws {
        try touch(paths.systemWav)
        XCTAssertEqual(AudioSourceResolver.resolveSources(paths: paths).system,
                       paths.systemWav)
        try touch(paths.systemNormalized)
        XCTAssertEqual(AudioSourceResolver.resolveSources(paths: paths).system,
                       paths.systemNormalized)
        try touch(paths.systemM4a)
        let s = AudioSourceResolver.resolveSources(paths: paths)
        XCTAssertEqual(s.system, paths.systemM4a)
        XCTAssertNil(s.mic, "a stream with no file must resolve to nil")
        XCTAssertEqual(s.urls, [paths.systemM4a])
    }

    /// A 0-byte stream (aborted recording stub) is excluded per stream, exactly
    /// like `resolve` excludes it globally.
    func test_resolveSources_zeroByteStreamResolvesToNil() throws {
        try Data().write(to: paths.micM4a)
        try touch(paths.systemM4a)
        let s = AudioSourceResolver.resolveSources(paths: paths)
        XCTAssertNil(s.mic)
        XCTAssertEqual(s.system, paths.systemM4a)
    }

    /// A directory named `mic.m4a`, or an unreadable stub, must not be handed to
    /// `AVAudioPlayer` as if it were audio — but the resolver's job is only
    /// existence; emptiness is the one cheap sanity check worth making, because
    /// `Recorder` creates the WAV header before any audio is written.
    func test_zeroByteFilesAreSkipped() throws {
        try Data().write(to: paths.micM4a)
        try touch(paths.systemM4a)
        XCTAssertEqual(AudioSourceResolver.resolve(paths: paths), paths.systemM4a)
    }
}
